import requests
import json
import urllib.parse

artists = [
    "Childish Gambino",
    "Janelle Monáe",
    "The 1975",
    "DJ Snake",
    "Diplo",
    "RÜFÜS DU SOL",
    "BLACKPINK",
    "Anderson Paak",
    "Kacey Musgraves",
    "Juice WRLD",
    "Ella Mai",
    "Los Tucanes De Tijuana",
    "FISHER",
    "Jaden Smith",
    "Nina Kraviz",
    "Rosalía",
    "Gorgon City",
    "Mon Laferte",
    "Khruangbin",
    "Kayzo",
    "dvsn",
    "King Princess",
    "Chris Lake",
    "Jauz",
    "The Interrupters",
    "Hot Since 82",
    "Charlotte Gainsbourg",
    "SOPHIE",
    "Nicole Moudaber",
    "Tierra Whack",
    "Polo & Pan",
    "Beach Fossils",
    "Yellow Days",
    "The Frights",
    "Nora En Pure",
    "Yves Tumor",
    "SG Lewis",
    "Kero Kero Bonito",
    "JPEGMAFIA",
    "Calypso Rose",
    "Nic Fanciulli",
    "Kölsch",
    "CamelPhat",
    "Let's Eat Grandma",
    "Anna Lunoe",
    "Amelie Lens",
    "Hurray for the Riff Raff",
    "Walker & Royce",
    "Turnstile",
    "RAT BOY",
    "88Glam",
    "Ross From Friends",
    "Lauren Lane",
    "Still Woozy",
    "Bakar",
    "https://api.spotify.com/v1/artists/6zsJjoCtL1WByG0VsuFWzR",
    "Tomasa del Real",
    "Las Robertas",
    "Dave P.",
    "Tame Impala",
    "Solange",
    "Kid Cudi",
    "Weezer",
    "Aphex Twin",
    "J Balvin",
    "Billie Eilish",
    "Bassnectar",
    "Four Tet",
    "Christine and the Queens",
    "Wiz Khalifa",
    "Mac DeMarco",
    "Bazzi",
    "Maggie Rogers",
    "Sheck Wes",
    "Gryffin",
    "Bob Moses",
    "Virgil Abloh",
    "Tale Of Us",
    "Mr. Eazi",
    "Sabrina Claudio",
    "Ty Segall",
    "White Fence",
    "Deep Dish",
    "Smino",
    "FKJ",
    "SiR",
    "Idris Elba",
    "Parcels",
    "Jain",
    "Turnover",
    "SALES",
    "Stephan Bodzin",
    "CloZee",
    "A R I Z O N A",
    "Murda Beatz",
    "Jambinai",
    "Âme",
    "CHON",
    "Little Simz",
    "Adriatique",
    "Lee Burridge",
    "The Garden",
    "Agoria",
    "Hop Along",
    "Shame",
    "Superorganism",
    "serpentwithfeet",
    "Ookay",
    "Steady Holiday",
    "Javiera Mena",
    "The Messthetics",
    "The Red Pears",
    "Ariana Grande",
    "Khalid",
    "Zedd",
    "Gesaffelstein",
    "Bad Bunny",
    "Dillon Francis",
    "CHVRCHES",
    "YG",
    "Cirez D",
    "Playboi Carti",
    "H.E.R.",
    "Blood Orange",
    "Pusha T",
    "Unknown Mortal Orchestra",
    "Kaytranada",
    "Gucci Gang",
    "Jon Hopkins",
    "SOFI TUKKER",
    "Burna Boy",
    "Lizzo",
    "Dermot Kennedy",
    "SOB X RBE",
    "Clairo",
    "NGHTMRE",
    "Perfume",
    "Boy Pablo",
    "Guy Gerber",
    "HYUKOH",
    "Emily King",
    "Dennis Lloyd",
    "Alice Merton",
    "Shallou",
    "070 Shake",
    "Soccer Mommy",
    "Rico Nasty",
    "Cola Boyy",
    "Wallows",
    "Mansionair",
    "Nocturnal Sunshine",
    "Dusky",
    "Yotto",
    "Patrice Bäumel",
    "Easy Life",
    "Jan Blomqvist",
    "U.S. Girls",
    "Iceage",
    "Men I Trust",
    "Charlotte de Witte",
    "Social House",
    "Ocho Ojos",
    "Razorbumps",
    "Tara Brooks"
]

artistOutput = []
headers = {"Authorization": "Bearer BQDs0oTc_jHbZ_wcRR993zlJG8j7pug3MBSACNI0ivNTrkW-p5t7nNLsGp1SY0Czy4EPsVG2wNhH4mK-NbFKSBcTgxAUydP1HlN9WVC5eQvGYGpabStn0oEh8c-Fh5__MRCANZIQMVjznd44ow"}

for artist in artists:
    if not "https://api" in artist:
        urlencodedArtist = urllib.parse.quote_plus(artist)
        req = requests.get(
            "https://api.spotify.com/v1/search?q=" + str(urlencodedArtist) + "&type=artist", headers=headers)
        res = req.json()
        firstResult = res["artists"]["items"][0]
        res["artists"]["items"] = [firstResult]
        artistOutput.append(res)
        print(artist)
    else:
        # Search for specific artist with given artistID with URL since some artists are not detected using their full name (Ex: Blond:ish)
        req = requests.get(artist, headers=headers)
        artistsDict = {}
        artistsDict['artists'] = {'items': [req.json()]}
        artistOutput.append(artistsDict)
        print(artist)

with open('artistsOutput.json', 'w') as outputFile:
    json.dump(artistOutput, outputFile, indent=4)
